# Generated by Django 5.1 on 2024-10-25 19:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Transactions", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
