# Generated by Django 4.1.13 on 2024-10-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Transactions", "0002_delete_transaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_date", models.DateField()),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("Deposit", "Deposit"), ("Withdraw", "Withdraw")],
                        max_length=10,
                    ),
                ),
                (
                    "transaction_category",
                    models.CharField(
                        choices=[
                            ("Shopping", "Shopping"),
                            ("Car Inspection", "Car Inspection"),
                            ("Travel Saving", "Travel Saving"),
                            ("Groceries", "Groceries"),
                            ("Utilities", "Utilities"),
                            ("Rent", "Rent"),
                            ("Entertainment", "Entertainment"),
                            ("Dining Out", "Dining Out"),
                            ("Health & Fitness", "Health & Fitness"),
                            ("Education", "Education"),
                            ("Clothing", "Clothing"),
                            ("Gifts", "Gifts"),
                            ("Home Improvement", "Home Improvement"),
                            ("Transportation", "Transportation"),
                            ("Subscription Services", "Subscription Services"),
                            ("Miscellaneous", "Miscellaneous"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "transaction_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
        ),
    ]
